/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as Red_confimexRouteImport } from './routes/red_confimex'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as ErpRouteImport } from './routes/erp'
import { Route as IndexRouteImport } from './routes/index'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const Red_confimexRoute = Red_confimexRouteImport.update({
  id: '/red_confimex',
  path: '/red_confimex',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRoute = ErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erp': typeof ErpRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/red_confimex': typeof Red_confimexRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erp': typeof ErpRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/red_confimex': typeof Red_confimexRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erp': typeof ErpRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/red_confimex': typeof Red_confimexRoute
  '/servicios': typeof ServiciosRoute
  '/testimonios': typeof TestimoniosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/erp'
    | '/quienes-somos'
    | '/red_confimex'
    | '/servicios'
    | '/testimonios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/erp'
    | '/quienes-somos'
    | '/red_confimex'
    | '/servicios'
    | '/testimonios'
  id:
    | '__root__'
    | '/'
    | '/erp'
    | '/quienes-somos'
    | '/red_confimex'
    | '/servicios'
    | '/testimonios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErpRoute: typeof ErpRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  Red_confimexRoute: typeof Red_confimexRoute
  ServiciosRoute: typeof ServiciosRoute
  TestimoniosRoute: typeof TestimoniosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red_confimex': {
      id: '/red_confimex'
      path: '/red_confimex'
      fullPath: '/red_confimex'
      preLoaderRoute: typeof Red_confimexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErpRoute: ErpRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  Red_confimexRoute: Red_confimexRoute,
  ServiciosRoute: ServiciosRoute,
  TestimoniosRoute: TestimoniosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
